INSERT INTO fish (name, price) VALUES ('African glass catfish', 17.58);
INSERT INTO fish (name, price) VALUES ('Airsac catfish', 21.56);
INSERT INTO fish (name, price) VALUES ('Alaska blackfish', 7.41);
INSERT INTO fish (name, price) VALUES ('Albacore', 10.92);
INSERT INTO fish (name, price) VALUES ('Alewife', 19.74);
INSERT INTO fish (name, price) VALUES ('Alfonsino', 11.25);
INSERT INTO fish (name, price) VALUES ('Alligatorfish', 27.7);
INSERT INTO fish (name, price) VALUES ('Alligator gar', 43.62);
INSERT INTO fish (name, price) VALUES ('Amberjack', 41.63);
INSERT INTO fish (name, price) VALUES ('American sole', 37.65);
INSERT INTO fish (name, price) VALUES ('Amur pike', 21.34);
INSERT INTO fish (name, price) VALUES ('Anchovy', 16.41);
INSERT INTO fish (name, price) VALUES ('Anemonefish', 10.18);
INSERT INTO fish (name, price) VALUES ('Pomacanthidae', 16.49);
INSERT INTO fish (name, price) VALUES ('Squatinidae', 17.92);
INSERT INTO fish (name, price) VALUES ('Pterophyllum', 28.41);
INSERT INTO fish (name, price) VALUES ('Atlantic pomfret', 36.6);
INSERT INTO fish (name, price) VALUES ('Atlantic spadefish', 35.22);
INSERT INTO fish (name, price) VALUES ('cave angelfish', 24.86);
INSERT INTO fish (name, price) VALUES ('Angler', 37.82);
INSERT INTO fish (name, price) VALUES ('Angler catfish', 42.16);
INSERT INTO fish (name, price) VALUES ('Anglerfish', 26.27);
INSERT INTO fish (name, price) VALUES ('Antarctic icefish', 36.36);
INSERT INTO fish (name, price) VALUES ('Antenna codlet', 31.83);
INSERT INTO fish (name, price) VALUES ('Arapaima', 5.25);
INSERT INTO fish (name, price) VALUES ('Archerfish', 20.14);
INSERT INTO fish (name, price) VALUES ('Armored searobin', 20.87);
INSERT INTO fish (name, price) VALUES ('Armorhead', 43.2);
INSERT INTO fish (name, price) VALUES ('Armorhead catfish', 26.57);
INSERT INTO fish (name, price) VALUES ('Arowana', 10.15);
INSERT INTO fish (name, price) VALUES ('Dysomma anguillare', 48.88);
INSERT INTO fish (name, price) VALUES ('Armored gurnard', 36.41);
INSERT INTO fish (name, price) VALUES ('Synaphobranchus kaupii', 8.44);
INSERT INTO fish (name, price) VALUES ('Ilyophis brunneus', 12.74);
INSERT INTO fish (name, price) VALUES ('Histiobranchus bathybius', 38.4);
INSERT INTO fish (name, price) VALUES ('Asiatic glassfish', 28.31);
INSERT INTO fish (name, price) VALUES ('Atka mackerel', 14.45);
INSERT INTO fish (name, price) VALUES ('Atlantic bonito', 19.26);
INSERT INTO fish (name, price) VALUES ('Atlantic cod', 46.79);
INSERT INTO fish (name, price) VALUES ('Atlantic salmon', 20.52);
INSERT INTO fish (name, price) VALUES ('Atlantic sharpnose shark', 46.31);
INSERT INTO fish (name, price) VALUES ('Atlantic saury', 27.43);
INSERT INTO fish (name, price) VALUES ('Atlantic silverside', 7.03);
INSERT INTO fish (name, price) VALUES ('Australian grayling', 48.78);
INSERT INTO fish (name, price) VALUES ('Australian herring', 46.69);
INSERT INTO fish (name, price) VALUES ('Australian lungfish', 38.54);
INSERT INTO fish (name, price) VALUES ('Arctic char', 49.16);
INSERT INTO fish (name, price) VALUES ('Ayu', 49.7);
INSERT INTO fish (name, price) VALUES ('Baikal oilfish', 19.06);
INSERT INTO fish (name, price) VALUES ('Australian prowfish', 6.39);
INSERT INTO fish (name, price) VALUES ('Ballan wrasse', 42.31);
INSERT INTO fish (name, price) VALUES ('Bamboo shark', 11.58);
INSERT INTO fish (name, price) VALUES ('Bala shark', 36.64);
INSERT INTO fish (name, price) VALUES ('Bandfish', 16.14);
INSERT INTO fish (name, price) VALUES ('Banjo', 17.43);
INSERT INTO fish (name, price) VALUES ('Banded killifish', 49.4);
INSERT INTO fish (name, price) VALUES ('Banjo catfish', 48.39);
INSERT INTO fish (name, price) VALUES ('Barb', 38.49);
INSERT INTO fish (name, price) VALUES ('Barbel', 22.69);
INSERT INTO fish (name, price) VALUES ('Barbeled dragonfish', 49.73);
INSERT INTO fish (name, price) VALUES ('Barbeled houndshark', 42.49);
INSERT INTO fish (name, price) VALUES ('Barbel-less catfish', 35.12);
INSERT INTO fish (name, price) VALUES ('Barracuda', 8.61);
INSERT INTO fish (name, price) VALUES ('Barracudina', 33.58);
INSERT INTO fish (name, price) VALUES ('Barramundi', 47.5);
INSERT INTO fish (name, price) VALUES ('Barred danio', 20.95);
INSERT INTO fish (name, price) VALUES ('Barreleye', 49.81);
INSERT INTO fish (name, price) VALUES ('Basking shark', 40.68);
INSERT INTO fish (name, price) VALUES ('Australasian salmon', 49.36);
INSERT INTO fish (name, price) VALUES ('Beachsalmon', 14.96);
INSERT INTO fish (name, price) VALUES ('Beaked salmon', 38.48);
INSERT INTO fish (name, price) VALUES ('Bat ray', 47.07);
INSERT INTO fish (name, price) VALUES ('Beardfish', 20.9);
INSERT INTO fish (name, price) VALUES ('Beluga sturgeon', 41.9);
INSERT INTO fish (name, price) VALUES ('Bengal danio', 27.8);
INSERT INTO fish (name, price) VALUES ('Betta', 40.93);
INSERT INTO fish (name, price) VALUES ('Bichir', 19.32);
INSERT INTO fish (name, price) VALUES ('Bicolor goat fish', 13.92);
INSERT INTO fish (name, price) VALUES ('Bigeye', 7.78);
INSERT INTO fish (name, price) VALUES ('Bigeye squaretail', 31.52);
INSERT INTO fish (name, price) VALUES ('Bighead carp', 5.05);
INSERT INTO fish (name, price) VALUES ('Bigmouth buffalo', 10.48);
INSERT INTO fish (name, price) VALUES ('Bigscale', 29.07);
INSERT INTO fish (name, price) VALUES ('Bigscale pomfret', 15.48);
INSERT INTO fish (name, price) VALUES ('Billfish', 6.92);
INSERT INTO fish (name, price) VALUES ('Bitterling', 16.23);
INSERT INTO fish (name, price) VALUES ('Black bass', 27.82);
INSERT INTO fish (name, price) VALUES ('Blackchin', 25.63);
INSERT INTO fish (name, price) VALUES ('Beaked sandfish', 45.61);
INSERT INTO fish (name, price) VALUES ('Black neon tetra', 48.9);
INSERT INTO fish (name, price) VALUES ('Blacktip reef shark', 9.64);
INSERT INTO fish (name, price) VALUES ('Black mackerel', 30.94);
INSERT INTO fish (name, price) VALUES ('Asian carp', 20.2);
INSERT INTO fish (name, price) VALUES ('Black scabbardfish', 14.05);
INSERT INTO fish (name, price) VALUES ('Black swallower', 11.4);
INSERT INTO fish (name, price) VALUES ('Black tetra', 10.42);
INSERT INTO fish (name, price) VALUES ('Black triggerfish', 15.69);
INSERT INTO fish (name, price) VALUES ('Blenny', 14.15);
INSERT INTO fish (name, price) VALUES ('Blind goby', 48.76);
INSERT INTO fish (name, price) VALUES ('Blind shark', 24.33);
INSERT INTO fish (name, price) VALUES ('Blowfish', 49.69);
INSERT INTO fish (name, price) VALUES ('Blue catfish', 22.05);
INSERT INTO fish (name, price) VALUES ('Blue danio', 26.78);
INSERT INTO fish (name, price) VALUES ('Blue-redstripe danio', 14.66);
INSERT INTO fish (name, price) VALUES ('Blue eye trevalla', 36.34);
INSERT INTO fish (name, price) VALUES ('Bluefish', 13.17);
INSERT INTO fish (name, price) VALUES ('Bluegill', 8.25);
INSERT INTO fish (name, price) VALUES ('Blue gourami', 10.32);
INSERT INTO fish (name, price) VALUES ('Blue shark', 29.24);
INSERT INTO fish (name, price) VALUES ('Blue whiting', 21.16);
INSERT INTO fish (name, price) VALUES ('Bangus', 25.78);
INSERT INTO fish (name, price) VALUES ('Black scalyfin', 40.22);
INSERT INTO fish (name, price) VALUES ('Blackfin Tuna', 29.17);
INSERT INTO fish (name, price) VALUES ('Bobtail snipe eel', 19.84);
INSERT INTO fish (name, price) VALUES ('Bocaccio', 28.46);
INSERT INTO fish (name, price) VALUES ('Bombay duck', 26.75);
INSERT INTO fish (name, price) VALUES ('Bonefish', 6.38);
INSERT INTO fish (name, price) VALUES ('Bonito', 40.71);
INSERT INTO fish (name, price) VALUES ('Bonnethead shark', 9.7);
INSERT INTO fish (name, price) VALUES ('Bonytail', 40.55);
INSERT INTO fish (name, price) VALUES ('Bonytongue', 40.7);
INSERT INTO fish (name, price) VALUES ('Bowfin', 8.54);
INSERT INTO fish (name, price) VALUES ('Boxfish', 27.3);
INSERT INTO fish (name, price) VALUES ('Bramble shark', 42.48);
INSERT INTO fish (name, price) VALUES ('Brill', 35.56);
INSERT INTO fish (name, price) VALUES ('Bristlemouth', 5.73);
INSERT INTO fish (name, price) VALUES ('Bristlenose catfish', 28.42);
INSERT INTO fish (name, price) VALUES ('Bluntnose knifefish', 17.41);
INSERT INTO fish (name, price) VALUES ('Bronze corydoras', 32.83);
INSERT INTO fish (name, price) VALUES ('Brook lamprey', 27.15);
INSERT INTO fish (name, price) VALUES ('Brook stickleback', 42.95);
INSERT INTO fish (name, price) VALUES ('Brook trout', 6.26);
INSERT INTO fish (name, price) VALUES ('Brown trout', 13.29);
INSERT INTO fish (name, price) VALUES ('Buffalo fish', 38.48);
INSERT INTO fish (name, price) VALUES ('Bullhead shark', 22.41);
INSERT INTO fish (name, price) VALUES ('Bull shark', 38.24);
INSERT INTO fish (name, price) VALUES ('Bull trout', 17.97);
INSERT INTO fish (name, price) VALUES ('Burbot', 11.75);
INSERT INTO fish (name, price) VALUES ('Bumblebee goby', 28.3);
INSERT INTO fish (name, price) VALUES ('Buri', 21.23);
INSERT INTO fish (name, price) VALUES ('Burma danio', 14.48);
INSERT INTO fish (name, price) VALUES ('Butterfly ray', 13.35);
INSERT INTO fish (name, price) VALUES ('Butterflyfish', 21.03);
INSERT INTO fish (name, price) VALUES ('California flyingfish', 45.48);
INSERT INTO fish (name, price) VALUES ('California halibut', 28.83);
INSERT INTO fish (name, price) VALUES ('Canary rockfish', 30.36);
INSERT INTO fish (name, price) VALUES ('Candiru', 31.24);
INSERT INTO fish (name, price) VALUES ('Candlefish', 47.58);
INSERT INTO fish (name, price) VALUES ('Capelin', 42.46);
INSERT INTO fish (name, price) VALUES ('Cardinalfish', 26.23);
INSERT INTO fish (name, price) VALUES ('Cardinal tetra', 36.86);
INSERT INTO fish (name, price) VALUES ('Carpetshark', 13.63);
INSERT INTO fish (name, price) VALUES ('Carpsucker', 44.23);
INSERT INTO fish (name, price) VALUES ('Catfish', 25.98);
INSERT INTO fish (name, price) VALUES ('Catla', 15.35);
INSERT INTO fish (name, price) VALUES ('Cat shark', 42.37);
INSERT INTO fish (name, price) VALUES ('Celebes rainbowfish', 33.4);
INSERT INTO fish (name, price) VALUES ('Central mudminnow', 38.63);
INSERT INTO fish (name, price) VALUES ('Chain pickerel', 36.11);
INSERT INTO fish (name, price) VALUES ('Channel bass', 28.79);
INSERT INTO fish (name, price) VALUES ('Channel catfish', 40.95);
INSERT INTO fish (name, price) VALUES ('Char', 41.66);
INSERT INTO fish (name, price) VALUES ('Chimaera', 11.36);
INSERT INTO fish (name, price) VALUES ('Chinook salmon', 40.87);
INSERT INTO fish (name, price) VALUES ('Cherubfish', 48.45);
INSERT INTO fish (name, price) VALUES ('Chubsucker', 49.53);
INSERT INTO fish (name, price) VALUES ('Chum salmon', 44.69);
INSERT INTO fish (name, price) VALUES ('Cichlid', 47.87);
INSERT INTO fish (name, price) VALUES ('Cisco', 13.0);
INSERT INTO fish (name, price) VALUES ('Climbing catfish', 9.86);
INSERT INTO fish (name, price) VALUES ('Climbing gourami', 41.63);
INSERT INTO fish (name, price) VALUES ('Clingfish', 46.54);
INSERT INTO fish (name, price) VALUES ('Clownfish', 25.52);
INSERT INTO fish (name, price) VALUES ('Clown loach', 7.16);
INSERT INTO fish (name, price) VALUES ('Clown triggerfish', 24.49);
INSERT INTO fish (name, price) VALUES ('Cobia', 7.75);
INSERT INTO fish (name, price) VALUES ('Cod', 38.89);
INSERT INTO fish (name, price) VALUES ('Codlet', 13.8);
INSERT INTO fish (name, price) VALUES ('Coelacanth', 9.06);
INSERT INTO fish (name, price) VALUES ('Coho salmon', 26.49);
INSERT INTO fish (name, price) VALUES ('Collared carpetshark', 25.62);
INSERT INTO fish (name, price) VALUES ('Collared dogfish', 11.0);
INSERT INTO fish (name, price) VALUES ('Colorado squawfish', 23.85);
INSERT INTO fish (name, price) VALUES ('Combfish', 48.3);
INSERT INTO fish (name, price) VALUES ('Combtail gourami', 46.74);
INSERT INTO fish (name, price) VALUES ('Combtooth blenny', 17.1);
INSERT INTO fish (name, price) VALUES ('Common carp', 37.12);
INSERT INTO fish (name, price) VALUES ('Common tunny', 20.43);
INSERT INTO fish (name, price) VALUES ('Convict blenny', 5.73);
INSERT INTO fish (name, price) VALUES ('Convict cichlid', 31.4);
INSERT INTO fish (name, price) VALUES ('Cookie-cutter shark', 5.5);
INSERT INTO fish (name, price) VALUES ('Coolie loach', 20.59);
INSERT INTO fish (name, price) VALUES ('Cornetfish', 42.63);
INSERT INTO fish (name, price) VALUES ('Cowfish', 47.45);
INSERT INTO fish (name, price) VALUES ('Cownose ray', 36.95);
INSERT INTO fish (name, price) VALUES ('Cow shark', 11.96);
INSERT INTO fish (name, price) VALUES ('Crappie', 40.17);
INSERT INTO fish (name, price) VALUES ('Creek chub', 42.74);
INSERT INTO fish (name, price) VALUES ('Crestfish', 8.86);
INSERT INTO fish (name, price) VALUES ('Crevice kelpfish', 30.37);
INSERT INTO fish (name, price) VALUES ('Croaker', 47.4);
INSERT INTO fish (name, price) VALUES ('Crocodile icefish', 41.88);
INSERT INTO fish (name, price) VALUES ('Crocodile shark', 10.65);
INSERT INTO fish (name, price) VALUES ('Crucian carp', 49.97);
INSERT INTO fish (name, price) VALUES ('Cuckoo wrasse', 16.82);
INSERT INTO fish (name, price) VALUES ('Cusk', 48.26);
INSERT INTO fish (name, price) VALUES ('Cusk-eel', 22.43);
INSERT INTO fish (name, price) VALUES ('Cutlassfish', 48.43);
INSERT INTO fish (name, price) VALUES ('Cutthroat eel', 14.15);
INSERT INTO fish (name, price) VALUES ('Cutthroat trout', 30.68);
INSERT INTO fish (name, price) VALUES ('Dab', 29.16);
INSERT INTO fish (name, price) VALUES ('Daggertooth pike conger', 13.62);
INSERT INTO fish (name, price) VALUES ('Danio', 24.42);
INSERT INTO fish (name, price) VALUES ('Darter', 21.31);
INSERT INTO fish (name, price) VALUES ('Dartfish', 5.18);
INSERT INTO fish (name, price) VALUES ('Dealfish', 27.49);
INSERT INTO fish (name, price) VALUES ('Death Valley pupfish', 19.95);
INSERT INTO fish (name, price) VALUES ('Deep sea smelt', 12.41);
INSERT INTO fish (name, price) VALUES ('Deepwater cardinalfish', 30.2);
INSERT INTO fish (name, price) VALUES ('Deepwater flathead', 21.37);
INSERT INTO fish (name, price) VALUES ('Deepwater stingray', 23.27);
INSERT INTO fish (name, price) VALUES ('Delta smelt', 43.1);
INSERT INTO fish (name, price) VALUES ('Denticle herring', 31.07);
INSERT INTO fish (name, price) VALUES ('Desert pupfish', 27.98);
INSERT INTO fish (name, price) VALUES ('Devario', 31.08);
INSERT INTO fish (name, price) VALUES ('Dhufish', 11.35);
INSERT INTO fish (name, price) VALUES ('Discus', 39.58);
INSERT INTO fish (name, price) VALUES ('Dogfish shark', 48.46);
INSERT INTO fish (name, price) VALUES ('Dogteeth tetra', 29.57);
INSERT INTO fish (name, price) VALUES ('Dojo loach', 24.9);
INSERT INTO fish (name, price) VALUES ('Dolly Varden trout', 43.17);
INSERT INTO fish (name, price) VALUES ('Dolphin fish', 7.03);
INSERT INTO fish (name, price) VALUES ('Dorab wolf-herring', 30.76);
INSERT INTO fish (name, price) VALUES ('Dottyback', 37.93);
INSERT INTO fish (name, price) VALUES ('Dragonet', 20.86);
INSERT INTO fish (name, price) VALUES ('Dragon goby', 24.47);
INSERT INTO fish (name, price) VALUES ('Driftfish', 24.97);
INSERT INTO fish (name, price) VALUES ('Driftwood catfish', 38.62);
INSERT INTO fish (name, price) VALUES ('Drum', 27.27);
INSERT INTO fish (name, price) VALUES ('Duckbill', 27.16);
INSERT INTO fish (name, price) VALUES ('Duckbill eel', 11.78);
INSERT INTO fish (name, price) VALUES ('Dusky grouper', 34.93);
INSERT INTO fish (name, price) VALUES ('Dusky shark', 12.96);
INSERT INTO fish (name, price) VALUES ('Dwarf gourami', 31.83);
INSERT INTO fish (name, price) VALUES ('Dwarf loach', 9.82);
INSERT INTO fish (name, price) VALUES ('Eagle ray', 34.75);
INSERT INTO fish (name, price) VALUES ('Earthworm eel', 12.96);
INSERT INTO fish (name, price) VALUES ('Eel', 8.21);
INSERT INTO fish (name, price) VALUES ('Eel cod', 49.63);
INSERT INTO fish (name, price) VALUES ('Eel-goby', 38.14);
INSERT INTO fish (name, price) VALUES ('Eelpout', 31.24);
INSERT INTO fish (name, price) VALUES ('Eeltail catfish', 26.52);
INSERT INTO fish (name, price) VALUES ('Elasmobranch', 43.5);
INSERT INTO fish (name, price) VALUES ('Aholehole', 49.91);
INSERT INTO fish (name, price) VALUES ('Airbreathing catfish', 7.14);
INSERT INTO fish (name, price) VALUES ('African lungfish', 9.78);
INSERT INTO fish (name, price) VALUES ('Electric ray', 27.18);
INSERT INTO fish (name, price) VALUES ('Electric eel', 12.82);
INSERT INTO fish (name, price) VALUES ('Electric knifefish', 19.59);
INSERT INTO fish (name, price) VALUES ('Ember parrotfish', 21.04);
INSERT INTO fish (name, price) VALUES ('Emerald catfish', 27.56);
INSERT INTO fish (name, price) VALUES ('Emperor angelfish', 7.57);
INSERT INTO fish (name, price) VALUES ('Emperor bream', 23.85);
INSERT INTO fish (name, price) VALUES ('Escolar', 42.08);
INSERT INTO fish (name, price) VALUES ('Eucla cod', 35.47);
INSERT INTO fish (name, price) VALUES ('Eulachon', 30.87);
INSERT INTO fish (name, price) VALUES ('European chub', 11.13);
INSERT INTO fish (name, price) VALUES ('European eel', 33.65);
INSERT INTO fish (name, price) VALUES ('European flounder', 46.19);
INSERT INTO fish (name, price) VALUES ('European minnow', 33.48);
INSERT INTO fish (name, price) VALUES ('European perch', 38.61);
INSERT INTO fish (name, price) VALUES ('False brotula', 27.48);
INSERT INTO fish (name, price) VALUES ('False cat shark', 14.17);
INSERT INTO fish (name, price) VALUES ('False trevally', 14.37);
INSERT INTO fish (name, price) VALUES ('Fangtooth', 23.43);
INSERT INTO fish (name, price) VALUES ('Fathead sculpin', 32.26);
INSERT INTO fish (name, price) VALUES ('Featherback', 9.14);
INSERT INTO fish (name, price) VALUES ('Fire goby', 29.44);
INSERT INTO fish (name, price) VALUES ('Filefish', 20.0);
INSERT INTO fish (name, price) VALUES ('Finback cat shark', 38.91);
INSERT INTO fish (name, price) VALUES ('Fingerfish', 49.02);
INSERT INTO fish (name, price) VALUES ('Fire bar danio', 21.16);
INSERT INTO fish (name, price) VALUES ('Flagblenny', 35.98);
INSERT INTO fish (name, price) VALUES ('Flagfin', 42.5);
INSERT INTO fish (name, price) VALUES ('Flagfish', 42.62);
INSERT INTO fish (name, price) VALUES ('Flagtail', 38.03);
INSERT INTO fish (name, price) VALUES ('Flatfish', 11.31);
INSERT INTO fish (name, price) VALUES ('Flathead catfish', 28.6);
INSERT INTO fish (name, price) VALUES ('Flier', 47.94);
INSERT INTO fish (name, price) VALUES ('Flying gurnard', 49.09);
INSERT INTO fish (name, price) VALUES ('Flying fish', 33.91);
INSERT INTO fish (name, price) VALUES ('Footballfish', 8.15);
INSERT INTO fish (name, price) VALUES ('Forehead brooder', 23.86);
INSERT INTO fish (name, price) VALUES ('Four-eyed fish', 6.52);
INSERT INTO fish (name, price) VALUES ('French angelfish', 36.85);
INSERT INTO fish (name, price) VALUES ('Freshwater eel', 19.83);
INSERT INTO fish (name, price) VALUES ('Freshwater hatchetfish', 30.72);
INSERT INTO fish (name, price) VALUES ('Frigate mackerel', 6.7);
INSERT INTO fish (name, price) VALUES ('Frilled shark', 32.3);
INSERT INTO fish (name, price) VALUES ('Frogfish', 14.82);
INSERT INTO fish (name, price) VALUES ('Frogmouth catfish', 41.31);
INSERT INTO fish (name, price) VALUES ('Fusilier fish', 11.31);
INSERT INTO fish (name, price) VALUES ('Galjoen fish', 34.67);
INSERT INTO fish (name, price) VALUES ('Ganges shark', 28.43);
INSERT INTO fish (name, price) VALUES ('Gar', 31.53);
INSERT INTO fish (name, price) VALUES ('Garden eel', 10.68);
INSERT INTO fish (name, price) VALUES ('Electric catfish', 18.78);
INSERT INTO fish (name, price) VALUES ('Garpike', 31.7);
INSERT INTO fish (name, price) VALUES ('Ghost flathead', 45.89);
INSERT INTO fish (name, price) VALUES ('Ghost knifefish', 36.6);
INSERT INTO fish (name, price) VALUES ('Ghost pipefish', 13.62);
INSERT INTO fish (name, price) VALUES ('Ghost shark', 25.68);
INSERT INTO fish (name, price) VALUES ('Ghoul', 10.34);
INSERT INTO fish (name, price) VALUES ('Giant danio', 33.9);
INSERT INTO fish (name, price) VALUES ('Giant gourami', 17.12);
INSERT INTO fish (name, price) VALUES ('Giant sea bass', 31.69);
INSERT INTO fish (name, price) VALUES ('Gibberfish', 28.6);
INSERT INTO fish (name, price) VALUES ('Gila trout', 47.4);
INSERT INTO fish (name, price) VALUES ('Gizzard shad', 44.24);
INSERT INTO fish (name, price) VALUES ('Glass knifefish', 20.59);
INSERT INTO fish (name, price) VALUES ('Glowlight danio', 13.96);
INSERT INTO fish (name, price) VALUES ('Goatfish', 11.01);
INSERT INTO fish (name, price) VALUES ('Goblin shark', 39.02);
INSERT INTO fish (name, price) VALUES ('Golden dojo', 31.23);
INSERT INTO fish (name, price) VALUES ('Golden loach', 41.55);
INSERT INTO fish (name, price) VALUES ('Golden shiner', 22.81);
INSERT INTO fish (name, price) VALUES ('Golden trout', 33.58);
INSERT INTO fish (name, price) VALUES ('Goldfish', 18.55);
INSERT INTO fish (name, price) VALUES ('Gombessa', 38.82);
INSERT INTO fish (name, price) VALUES ('Flabby whale fish', 17.62);
INSERT INTO fish (name, price) VALUES ('Gopher rockfish', 34.63);
INSERT INTO fish (name, price) VALUES ('Gourami', 48.53);
INSERT INTO fish (name, price) VALUES ('Grass carp', 6.01);
INSERT INTO fish (name, price) VALUES ('Graveldiver', 34.01);
INSERT INTO fish (name, price) VALUES ('Gray reef shark', 13.79);
INSERT INTO fish (name, price) VALUES ('Great white shark', 27.82);
INSERT INTO fish (name, price) VALUES ('Green swordtail', 8.0);
INSERT INTO fish (name, price) VALUES ('Greeneye', 24.3);
INSERT INTO fish (name, price) VALUES ('Greenling', 39.8);
INSERT INTO fish (name, price) VALUES ('Goosefish', 25.02);
INSERT INTO fish (name, price) VALUES ('Ground shark', 22.87);
INSERT INTO fish (name, price) VALUES ('Grouper', 10.82);
INSERT INTO fish (name, price) VALUES ('Grunion', 7.92);
INSERT INTO fish (name, price) VALUES ('Grunter', 44.77);
INSERT INTO fish (name, price) VALUES ('Grunt sculpin', 31.08);
INSERT INTO fish (name, price) VALUES ('Guitarfish', 48.07);
INSERT INTO fish (name, price) VALUES ('Gulf menhaden', 45.66);
INSERT INTO fish (name, price) VALUES ('Gulper eel', 45.43);
INSERT INTO fish (name, price) VALUES ('Gulper', 20.0);
INSERT INTO fish (name, price) VALUES ('Gunnel', 24.72);
INSERT INTO fish (name, price) VALUES ('Guppy', 40.94);
INSERT INTO fish (name, price) VALUES ('Grenadier', 14.69);
INSERT INTO fish (name, price) VALUES ('Haddock', 49.86);
INSERT INTO fish (name, price) VALUES ('Hagfish', 31.63);
INSERT INTO fish (name, price) VALUES ('Halfbeak', 30.41);
INSERT INTO fish (name, price) VALUES ('Halfmoon', 24.54);
INSERT INTO fish (name, price) VALUES ('Halosaur', 37.65);
INSERT INTO fish (name, price) VALUES ('Hamlet', 45.36);
INSERT INTO fish (name, price) VALUES ('Hammerhead shark', 44.4);
INSERT INTO fish (name, price) VALUES ('Hammerjaw', 22.91);
INSERT INTO fish (name, price) VALUES ('Handfish', 13.89);
INSERT INTO fish (name, price) VALUES ('Hardhead catfish', 31.84);
INSERT INTO fish (name, price) VALUES ('Harelip sucker', 9.74);
INSERT INTO fish (name, price) VALUES ('Hawkfish', 29.71);
INSERT INTO fish (name, price) VALUES ('Herring', 7.82);
INSERT INTO fish (name, price) VALUES ('Herring smelt', 20.93);
INSERT INTO fish (name, price) VALUES ('Hickory Shad', 18.54);
INSERT INTO fish (name, price) VALUES ('Hillstream loach', 13.63);
INSERT INTO fish (name, price) VALUES ('Hog sucker', 25.81);
INSERT INTO fish (name, price) VALUES ('Hoki', 49.78);
INSERT INTO fish (name, price) VALUES ('Horn shark', 15.25);
INSERT INTO fish (name, price) VALUES ('Horsefish', 10.41);
INSERT INTO fish (name, price) VALUES ('Houndshark', 32.36);
INSERT INTO fish (name, price) VALUES ('Huchen', 37.3);
INSERT INTO fish (name, price) VALUES ('Humuhumunukunukuapuaa', 45.43);
INSERT INTO fish (name, price) VALUES ('Hussar', 6.36);
INSERT INTO fish (name, price) VALUES ('Icefish', 32.48);
INSERT INTO fish (name, price) VALUES ('Ide', 45.02);
INSERT INTO fish (name, price) VALUES ('Ilish/Hilsha', 5.58);
INSERT INTO fish (name, price) VALUES ('Inconnu', 34.59);
INSERT INTO fish (name, price) VALUES ('Jack Dempsey', 19.61);
INSERT INTO fish (name, price) VALUES ('Japanese eel', 23.42);
INSERT INTO fish (name, price) VALUES ('Hairtail', 47.36);
INSERT INTO fish (name, price) VALUES ('Jellynose fish', 20.63);
INSERT INTO fish (name, price) VALUES ('Jewelfish', 43.42);
INSERT INTO fish (name, price) VALUES ('Jawfish', 5.66);
INSERT INTO fish (name, price) VALUES ('John Dory', 11.49);
INSERT INTO fish (name, price) VALUES ('Kafue pike', 19.29);
INSERT INTO fish (name, price) VALUES ('Kahawai', 35.63);
INSERT INTO fish (name, price) VALUES ('Kaluga', 44.83);
INSERT INTO fish (name, price) VALUES ('Kanyu', 9.33);
INSERT INTO fish (name, price) VALUES ('Kelp perch', 18.07);
INSERT INTO fish (name, price) VALUES ('King-of-the-salmon', 5.19);
INSERT INTO fish (name, price) VALUES ('Kissing gourami', 21.31);
INSERT INTO fish (name, price) VALUES ('Knifejaw', 45.28);
INSERT INTO fish (name, price) VALUES ('Koi', 5.62);
INSERT INTO fish (name, price) VALUES ('Kokanee', 6.15);
INSERT INTO fish (name, price) VALUES ('Elephantnose fish', 43.25);
INSERT INTO fish (name, price) VALUES ('Labyrinth fish', 24.68);
INSERT INTO fish (name, price) VALUES ('Ladyfish', 7.89);
INSERT INTO fish (name, price) VALUES ('Lake chub', 32.58);
INSERT INTO fish (name, price) VALUES ('Lake trout', 17.73);
INSERT INTO fish (name, price) VALUES ('Lake whitefish', 16.12);
INSERT INTO fish (name, price) VALUES ('Lamprey', 20.35);
INSERT INTO fish (name, price) VALUES ('Lancetfish', 5.22);
INSERT INTO fish (name, price) VALUES ('Lanternfish', 25.53);
INSERT INTO fish (name, price) VALUES ('Largemouth bass', 49.35);
INSERT INTO fish (name, price) VALUES ('Lefteye flounder', 37.47);
INSERT INTO fish (name, price) VALUES ('Lemon shark', 14.93);
INSERT INTO fish (name, price) VALUES ('Lemon sole', 21.67);
INSERT INTO fish (name, price) VALUES ('Lemon tetra', 21.2);
INSERT INTO fish (name, price) VALUES ('Lenok', 12.73);
INSERT INTO fish (name, price) VALUES ('Leopard danio', 17.16);
INSERT INTO fish (name, price) VALUES ('Limia', 8.55);
INSERT INTO fish (name, price) VALUES ('Lined sole', 6.33);
INSERT INTO fish (name, price) VALUES ('Lizardfish', 33.65);
INSERT INTO fish (name, price) VALUES ('Loach catfish', 30.07);
INSERT INTO fish (name, price) VALUES ('Loach goby', 23.97);
INSERT INTO fish (name, price) VALUES ('Loach minnow', 26.59);
INSERT INTO fish (name, price) VALUES ('Longfin', 21.42);
INSERT INTO fish (name, price) VALUES ('Longfin escolar', 6.78);
INSERT INTO fish (name, price) VALUES ('Longfin smelt', 22.08);
INSERT INTO fish (name, price) VALUES ('Long-finned char', 38.99);
INSERT INTO fish (name, price) VALUES ('Long-finned pike', 48.65);
INSERT INTO fish (name, price) VALUES ('Longjaw mudsucker', 47.54);
INSERT INTO fish (name, price) VALUES ('Kuhli loach', 43.52);
INSERT INTO fish (name, price) VALUES ('Longnose chimaera', 49.23);
INSERT INTO fish (name, price) VALUES ('Longnose dace', 48.93);
INSERT INTO fish (name, price) VALUES ('Longnose lancetfish', 33.09);
INSERT INTO fish (name, price) VALUES ('Longnose sucker', 29.22);
INSERT INTO fish (name, price) VALUES ('Long-whiskered catfish', 16.35);
INSERT INTO fish (name, price) VALUES ('Loosejaw', 22.52);
INSERT INTO fish (name, price) VALUES ('Jewel tetra', 18.3);
INSERT INTO fish (name, price) VALUES ('Louvar', 15.82);
INSERT INTO fish (name, price) VALUES ('Loweye catfish', 16.77);
INSERT INTO fish (name, price) VALUES ('Luderick', 41.15);
INSERT INTO fish (name, price) VALUES ('Luminous hake', 40.16);
INSERT INTO fish (name, price) VALUES ('Garibaldi', 32.48);
INSERT INTO fish (name, price) VALUES ('Lost River sucker', 5.67);
INSERT INTO fish (name, price) VALUES ('Longneck eel', 24.32);
INSERT INTO fish (name, price) VALUES ('Mackerel shark', 19.38);
INSERT INTO fish (name, price) VALUES ('Madtom', 37.14);
INSERT INTO fish (name, price) VALUES ('Mahi-mahi', 15.52);
INSERT INTO fish (name, price) VALUES ('Mahseer', 5.94);
INSERT INTO fish (name, price) VALUES ('Mail-cheeked fish', 9.84);
INSERT INTO fish (name, price) VALUES ('Mako shark', 15.81);
INSERT INTO fish (name, price) VALUES ('Manefish', 44.63);
INSERT INTO fish (name, price) VALUES ('Man-of-war fish', 29.06);
INSERT INTO fish (name, price) VALUES ('Manta ray', 24.6);
INSERT INTO fish (name, price) VALUES ('Lungfish', 38.27);
INSERT INTO fish (name, price) VALUES ('Mackerel', 31.87);
INSERT INTO fish (name, price) VALUES ('Marlin', 41.57);
INSERT INTO fish (name, price) VALUES ('Medaka', 35.17);
INSERT INTO fish (name, price) VALUES ('Medusafish', 5.56);
INSERT INTO fish (name, price) VALUES ('Megamouth shark', 39.0);
INSERT INTO fish (name, price) VALUES ('Menhaden', 22.68);
INSERT INTO fish (name, price) VALUES ('Merluccid hake', 12.75);
INSERT INTO fish (name, price) VALUES ('Mexican golden trout', 29.72);
INSERT INTO fish (name, price) VALUES ('Midshipman fish', 47.54);
INSERT INTO fish (name, price) VALUES ('Milkfish', 18.22);
INSERT INTO fish (name, price) VALUES ('Minnow', 42.35);
INSERT INTO fish (name, price) VALUES ('Minnow of the deep', 26.59);
INSERT INTO fish (name, price) VALUES ('Modoc sucker', 14.5);
INSERT INTO fish (name, price) VALUES ('Mojarra', 14.35);
INSERT INTO fish (name, price) VALUES ('Mola mola', 9.98);
INSERT INTO fish (name, price) VALUES ('Monkeyface prickleback', 27.96);
INSERT INTO fish (name, price) VALUES ('Monkfish', 6.32);
INSERT INTO fish (name, price) VALUES ('Mooneye', 26.23);
INSERT INTO fish (name, price) VALUES ('Moorish idol', 46.01);
INSERT INTO fish (name, price) VALUES ('Mora', 46.89);
INSERT INTO fish (name, price) VALUES ('Moray eel', 11.66);
INSERT INTO fish (name, price) VALUES ('Morid cod', 40.2);
INSERT INTO fish (name, price) VALUES ('Moses sole', 24.32);
INSERT INTO fish (name, price) VALUES ('Mosquitofish', 17.94);
INSERT INTO fish (name, price) VALUES ('Mozambique tilapia', 11.43);
INSERT INTO fish (name, price) VALUES ('Mrigal', 5.94);
INSERT INTO fish (name, price) VALUES ('Mud catfish', 18.82);
INSERT INTO fish (name, price) VALUES ('Mudskipper', 33.43);
INSERT INTO fish (name, price) VALUES ('Mudsucker', 18.05);
INSERT INTO fish (name, price) VALUES ('Mullet', 49.17);
INSERT INTO fish (name, price) VALUES ('Mummichog', 47.58);
INSERT INTO fish (name, price) VALUES ('Murray cod', 16.69);
INSERT INTO fish (name, price) VALUES ('Muskellunge', 36.8);
INSERT INTO fish (name, price) VALUES ('Mustache triggerfish', 10.6);
INSERT INTO fish (name, price) VALUES ('Mustard eel', 23.35);
INSERT INTO fish (name, price) VALUES ('Naked-back knifefish', 24.25);
INSERT INTO fish (name, price) VALUES ('Nase', 38.35);
INSERT INTO fish (name, price) VALUES ('Marblefish', 35.14);
INSERT INTO fish (name, price) VALUES ('Neon tetra', 29.72);
INSERT INTO fish (name, price) VALUES ('New World rivuline', 18.69);
INSERT INTO fish (name, price) VALUES ('New Zealand sand diver', 12.24);
INSERT INTO fish (name, price) VALUES ('Marine hatchetfish', 41.0);
INSERT INTO fish (name, price) VALUES ('Nibble fish', 30.85);
INSERT INTO fish (name, price) VALUES ('Needlefish', 22.01);
INSERT INTO fish (name, price) VALUES ('North American darter', 35.49);
INSERT INTO fish (name, price) VALUES ('North American freshwater catfish', 48.49);
INSERT INTO fish (name, price) VALUES ('North Pacific daggertooth', 28.3);
INSERT INTO fish (name, price) VALUES ('Northern anchovy', 35.02);
INSERT INTO fish (name, price) VALUES ('Northern clingfish', 32.2);
INSERT INTO fish (name, price) VALUES ('New Zealand smelt', 9.16);
INSERT INTO fish (name, price) VALUES ('Northern sea robin', 48.23);
INSERT INTO fish (name, price) VALUES ('Northern squawfish', 30.91);
INSERT INTO fish (name, price) VALUES ('Northern stargazer', 18.92);
INSERT INTO fish (name, price) VALUES ('Nurseryfish', 6.83);
INSERT INTO fish (name, price) VALUES ('Nurse shark', 26.24);
INSERT INTO fish (name, price) VALUES ('Oarfish', 37.79);
INSERT INTO fish (name, price) VALUES ('Ocean perch', 35.45);
INSERT INTO fish (name, price) VALUES ('Ocean sunfish', 36.28);
INSERT INTO fish (name, price) VALUES ('Oceanic whitetip shark', 40.79);
INSERT INTO fish (name, price) VALUES ('Oilfish', 44.53);
INSERT INTO fish (name, price) VALUES ('Oldwife', 6.49);
INSERT INTO fish (name, price) VALUES ('Old World knifefish', 32.97);
INSERT INTO fish (name, price) VALUES ('Olive flounder', 12.97);
INSERT INTO fish (name, price) VALUES ('Opah', 38.17);
INSERT INTO fish (name, price) VALUES ('Opaleye', 26.89);
INSERT INTO fish (name, price) VALUES ('Orange roughy', 14.92);
INSERT INTO fish (name, price) VALUES ('Orangespine unicorn fish', 36.32);
INSERT INTO fish (name, price) VALUES ('Orangestriped triggerfish', 42.22);
INSERT INTO fish (name, price) VALUES ('Orbicular batfish', 29.57);
INSERT INTO fish (name, price) VALUES ('Northern pike', 13.53);
INSERT INTO fish (name, price) VALUES ('Oregon chub', 46.5);
INSERT INTO fish (name, price) VALUES ('Orfe', 8.21);
INSERT INTO fish (name, price) VALUES ('Oriental loach', 12.54);
INSERT INTO fish (name, price) VALUES ('Oscar', 40.64);
INSERT INTO fish (name, price) VALUES ('Noodlefish', 25.17);
INSERT INTO fish (name, price) VALUES ('Pacific albacore', 35.92);
INSERT INTO fish (name, price) VALUES ('Pacific hake', 41.22);
INSERT INTO fish (name, price) VALUES ('Orbicular velvetfish', 33.59);
INSERT INTO fish (name, price) VALUES ('Pacific lamprey', 37.77);
INSERT INTO fish (name, price) VALUES ('Pacific salmon', 49.71);
INSERT INTO fish (name, price) VALUES ('Pacific saury', 47.04);
INSERT INTO fish (name, price) VALUES ('Pacific trout', 22.48);
INSERT INTO fish (name, price) VALUES ('Pacific viperfish', 6.26);
INSERT INTO fish (name, price) VALUES ('Paddlefish', 10.15);
INSERT INTO fish (name, price) VALUES ('Pancake batfish', 8.81);
INSERT INTO fish (name, price) VALUES ('Panga', 23.21);
INSERT INTO fish (name, price) VALUES ('Paradise fish', 5.38);
INSERT INTO fish (name, price) VALUES ('Parasitic catfish', 26.15);
INSERT INTO fish (name, price) VALUES ('Parore', 18.25);
INSERT INTO fish (name, price) VALUES ('Parrotfish', 11.32);
INSERT INTO fish (name, price) VALUES ('Peacock flounder', 18.55);
INSERT INTO fish (name, price) VALUES ('Peamouth', 25.79);
INSERT INTO fish (name, price) VALUES ('Pearleye', 7.45);
INSERT INTO fish (name, price) VALUES ('Pearlfish', 13.21);
INSERT INTO fish (name, price) VALUES ('Pearl danio', 25.12);
INSERT INTO fish (name, price) VALUES ('Pearl perch', 23.06);
INSERT INTO fish (name, price) VALUES ('Pelagic cod', 45.83);
INSERT INTO fish (name, price) VALUES ('Pelican eel', 24.34);
INSERT INTO fish (name, price) VALUES ('Pelican gulper', 17.97);
INSERT INTO fish (name, price) VALUES ('Pencil catfish', 16.98);
INSERT INTO fish (name, price) VALUES ('Pencilfish', 8.58);
INSERT INTO fish (name, price) VALUES ('Pencilsmelt', 23.3);
INSERT INTO fish (name, price) VALUES ('Peppered corydoras', 46.33);
INSERT INTO fish (name, price) VALUES ('Perch', 41.2);
INSERT INTO fish (name, price) VALUES ('Peters elephantnose fish', 31.53);
INSERT INTO fish (name, price) VALUES ('Pike conger', 11.69);
INSERT INTO fish (name, price) VALUES ('Pike eel', 15.73);
INSERT INTO fish (name, price) VALUES ('Pike', 37.09);
INSERT INTO fish (name, price) VALUES ('Pikeblenny', 32.82);
INSERT INTO fish (name, price) VALUES ('Lumpsucker', 16.32);
INSERT INTO fish (name, price) VALUES ('Owens pupfish', 25.37);
INSERT INTO fish (name, price) VALUES ('Pilot fish', 40.49);
INSERT INTO fish (name, price) VALUES ('Pineapplefish', 49.54);
INSERT INTO fish (name, price) VALUES ('Pineconefish', 37.42);
INSERT INTO fish (name, price) VALUES ('Pink salmon', 5.56);
INSERT INTO fish (name, price) VALUES ('PÃ­ntano', 8.73);
INSERT INTO fish (name, price) VALUES ('Pipefish', 32.6);
INSERT INTO fish (name, price) VALUES ('Piranha', 42.15);
INSERT INTO fish (name, price) VALUES ('Pirarucu', 8.13);
INSERT INTO fish (name, price) VALUES ('Pirate perch', 17.65);
INSERT INTO fish (name, price) VALUES ('Plaice', 40.91);
INSERT INTO fish (name, price) VALUES ('Plownose chimaera', 25.58);
INSERT INTO fish (name, price) VALUES ('Poacher', 28.82);
INSERT INTO fish (name, price) VALUES ('Pollyfish', 21.7);
INSERT INTO fish (name, price) VALUES ('Pollock', 8.62);
INSERT INTO fish (name, price) VALUES ('Pomfret', 24.89);
INSERT INTO fish (name, price) VALUES ('Pacific herring', 41.14);
INSERT INTO fish (name, price) VALUES ('Pompano dolphinfish', 27.09);
INSERT INTO fish (name, price) VALUES ('Ponyfish', 7.35);
INSERT INTO fish (name, price) VALUES ('Popeye catalufa', 8.85);
INSERT INTO fish (name, price) VALUES ('Porbeagle shark', 42.48);
INSERT INTO fish (name, price) VALUES ('Porcupinefish', 29.22);
INSERT INTO fish (name, price) VALUES ('Porgy', 41.7);
INSERT INTO fish (name, price) VALUES ('Port Jackson shark', 38.25);
INSERT INTO fish (name, price) VALUES ('Powen', 33.89);
INSERT INTO fish (name, price) VALUES ('Prickleback', 36.56);
INSERT INTO fish (name, price) VALUES ('Pricklefish', 48.42);
INSERT INTO fish (name, price) VALUES ('Prickly shark', 10.88);
INSERT INTO fish (name, price) VALUES ('Prowfish', 12.12);
INSERT INTO fish (name, price) VALUES ('Pufferfish', 10.94);
INSERT INTO fish (name, price) VALUES ('Pumpkinseed', 22.16);
INSERT INTO fish (name, price) VALUES ('Pupfish', 6.51);
INSERT INTO fish (name, price) VALUES ('Pygmy sunfish', 33.79);
INSERT INTO fish (name, price) VALUES ('Queen danio', 44.76);
INSERT INTO fish (name, price) VALUES ('Pikeperch', 43.27);
INSERT INTO fish (name, price) VALUES ('Pompano', 7.77);
INSERT INTO fish (name, price) VALUES ('Queen parrotfish', 41.03);
INSERT INTO fish (name, price) VALUES ('Quillfish', 31.55);
INSERT INTO fish (name, price) VALUES ('Rabbitfish', 39.2);
INSERT INTO fish (name, price) VALUES ('Raccoon butterfly fish', 25.79);
INSERT INTO fish (name, price) VALUES ('Ragfish', 9.42);
INSERT INTO fish (name, price) VALUES ('Rainbow trout', 23.48);
INSERT INTO fish (name, price) VALUES ('Rainbowfish', 33.53);
INSERT INTO fish (name, price) VALUES ('Rasbora', 18.03);
INSERT INTO fish (name, price) VALUES ('Ratfish', 7.8);
INSERT INTO fish (name, price) VALUES ('Rattail', 40.92);
INSERT INTO fish (name, price) VALUES ('Ray', 39.9);
INSERT INTO fish (name, price) VALUES ('Red grouper', 30.89);
INSERT INTO fish (name, price) VALUES ('Red salmon', 34.41);
INSERT INTO fish (name, price) VALUES ('Queen triggerfish', 8.28);
INSERT INTO fish (name, price) VALUES ('Redhorse sucker', 12.11);
INSERT INTO fish (name, price) VALUES ('Redlip blenny', 36.34);
INSERT INTO fish (name, price) VALUES ('Redmouth whalefish', 15.04);
INSERT INTO fish (name, price) VALUES ('Redtooth triggerfish', 42.44);
INSERT INTO fish (name, price) VALUES ('Red velvetfish', 34.05);
INSERT INTO fish (name, price) VALUES ('Red whalefish', 44.17);
INSERT INTO fish (name, price) VALUES ('Reedfish', 14.4);
INSERT INTO fish (name, price) VALUES ('Reef triggerfish', 26.13);
INSERT INTO fish (name, price) VALUES ('Remora', 46.32);
INSERT INTO fish (name, price) VALUES ('Requiem shark', 9.67);
INSERT INTO fish (name, price) VALUES ('Ribbon eel', 5.39);
INSERT INTO fish (name, price) VALUES ('Ribbon sawtail fish', 13.38);
INSERT INTO fish (name, price) VALUES ('Ribbonfish', 14.06);
INSERT INTO fish (name, price) VALUES ('Rice eel', 33.99);
INSERT INTO fish (name, price) VALUES ('Razorback sucker', 10.67);
INSERT INTO fish (name, price) VALUES ('Ridgehead', 46.34);
INSERT INTO fish (name, price) VALUES ('Riffle dace', 8.69);
INSERT INTO fish (name, price) VALUES ('Righteye flounder', 19.45);
INSERT INTO fish (name, price) VALUES ('Quillback', 39.83);
INSERT INTO fish (name, price) VALUES ('Redfin perch', 18.76);
INSERT INTO fish (name, price) VALUES ('River shark', 28.6);
INSERT INTO fish (name, price) VALUES ('River stingray', 12.51);
INSERT INTO fish (name, price) VALUES ('Rivuline', 40.21);
INSERT INTO fish (name, price) VALUES ('Roanoke bass', 28.75);
INSERT INTO fish (name, price) VALUES ('Rock bass', 11.57);
INSERT INTO fish (name, price) VALUES ('Rock beauty', 33.72);
INSERT INTO fish (name, price) VALUES ('Rock cod', 11.87);
INSERT INTO fish (name, price) VALUES ('Rockweed gunnel', 15.88);
INSERT INTO fish (name, price) VALUES ('Rohu', 31.59);
INSERT INTO fish (name, price) VALUES ('Ronquil', 16.29);
INSERT INTO fish (name, price) VALUES ('Roosterfish', 36.25);
INSERT INTO fish (name, price) VALUES ('Ropefish', 21.05);
INSERT INTO fish (name, price) VALUES ('Rough scad', 34.38);
INSERT INTO fish (name, price) VALUES ('Rough sculpin', 37.02);
INSERT INTO fish (name, price) VALUES ('Roughy', 30.52);
INSERT INTO fish (name, price) VALUES ('Roundhead', 38.63);
INSERT INTO fish (name, price) VALUES ('Round herring', 30.75);
INSERT INTO fish (name, price) VALUES ('Round stingray', 19.38);
INSERT INTO fish (name, price) VALUES ('Round whitefish', 17.82);
INSERT INTO fish (name, price) VALUES ('Rudd', 43.91);
INSERT INTO fish (name, price) VALUES ('Ruffe', 13.7);
INSERT INTO fish (name, price) VALUES ('Russian sturgeon', 29.86);
INSERT INTO fish (name, price) VALUES ('Saber-toothed blenny', 39.85);
INSERT INTO fish (name, price) VALUES ('Sabertooth fish', 24.41);
INSERT INTO fish (name, price) VALUES ('Sacramento blackfish', 43.8);
INSERT INTO fish (name, price) VALUES ('Sacramento splittail', 40.07);
INSERT INTO fish (name, price) VALUES ('Sailfin silverside', 6.17);
INSERT INTO fish (name, price) VALUES ('Sailfish', 44.45);
INSERT INTO fish (name, price) VALUES ('Salamanderfish', 25.67);
INSERT INTO fish (name, price) VALUES ('Salmon', 49.24);
INSERT INTO fish (name, price) VALUES ('Salmon shark', 6.85);
INSERT INTO fish (name, price) VALUES ('Sandbar shark', 37.97);
INSERT INTO fish (name, price) VALUES ('Sandburrower', 44.67);
INSERT INTO fish (name, price) VALUES ('Sand dab', 32.53);
INSERT INTO fish (name, price) VALUES ('Sand goby', 27.49);
INSERT INTO fish (name, price) VALUES ('Sand knifefish', 28.39);
INSERT INTO fish (name, price) VALUES ('Sand lance', 16.0);
INSERT INTO fish (name, price) VALUES ('Sandperch', 27.38);
INSERT INTO fish (name, price) VALUES ('Sandroller', 40.99);
INSERT INTO fish (name, price) VALUES ('Sand stargazer', 22.19);
INSERT INTO fish (name, price) VALUES ('Sand tiger', 41.05);
INSERT INTO fish (name, price) VALUES ('Sand tilefish', 21.27);
INSERT INTO fish (name, price) VALUES ('Sandbar shark', 25.09);
INSERT INTO fish (name, price) VALUES ('Sarcastic fringehead', 26.1);
INSERT INTO fish (name, price) VALUES ('Sargassum fish', 34.91);
INSERT INTO fish (name, price) VALUES ('Sauger', 26.19);
INSERT INTO fish (name, price) VALUES ('Saury', 12.71);
INSERT INTO fish (name, price) VALUES ('Sawfish', 5.75);
INSERT INTO fish (name, price) VALUES ('Saw shark', 37.16);
INSERT INTO fish (name, price) VALUES ('Sawtooth eel', 11.61);
INSERT INTO fish (name, price) VALUES ('Scabbard fish', 5.36);
INSERT INTO fish (name, price) VALUES ('Scaly dragonfish', 45.79);
INSERT INTO fish (name, price) VALUES ('Scat', 37.58);
INSERT INTO fish (name, price) VALUES ('Scorpionfish', 7.81);
INSERT INTO fish (name, price) VALUES ('Scup', 49.81);
INSERT INTO fish (name, price) VALUES ('Sea bream', 29.56);
INSERT INTO fish (name, price) VALUES ('Sea catfish', 48.88);
INSERT INTO fish (name, price) VALUES ('Sea chub', 5.42);
INSERT INTO fish (name, price) VALUES ('Rio Grande perch', 12.54);
INSERT INTO fish (name, price) VALUES ('Sea dragon', 46.53);
INSERT INTO fish (name, price) VALUES ('Sea lamprey', 9.92);
INSERT INTO fish (name, price) VALUES ('Sea raven', 45.4);
INSERT INTO fish (name, price) VALUES ('Sea snail', 35.19);
INSERT INTO fish (name, price) VALUES ('Sea toad', 28.16);
INSERT INTO fish (name, price) VALUES ('Seahorse', 31.21);
INSERT INTO fish (name, price) VALUES ('Seamoth', 6.97);
INSERT INTO fish (name, price) VALUES ('Searobin', 5.46);
INSERT INTO fish (name, price) VALUES ('Sevan trout', 5.77);
INSERT INTO fish (name, price) VALUES ('Boafish', 12.98);
INSERT INTO fish (name, price) VALUES ('Shad', 5.37);
INSERT INTO fish (name, price) VALUES ('Shark', 43.15);
INSERT INTO fish (name, price) VALUES ('Sharksucker', 9.86);
INSERT INTO fish (name, price) VALUES ('Sharpnose puffer', 17.37);
INSERT INTO fish (name, price) VALUES ('Sheepshead minnow', 17.44);
INSERT INTO fish (name, price) VALUES ('Shortnose chimaera', 33.95);
INSERT INTO fish (name, price) VALUES ('Shortnose sucker', 19.25);
INSERT INTO fish (name, price) VALUES ('Shovelnose sturgeon', 35.41);
INSERT INTO fish (name, price) VALUES ('Shrimpfish', 27.11);
INSERT INTO fish (name, price) VALUES ('Siamese fighting fish', 48.84);
INSERT INTO fish (name, price) VALUES ('Sillago', 28.27);
INSERT INTO fish (name, price) VALUES ('Broadband dogfish', 8.16);
INSERT INTO fish (name, price) VALUES ('Silver dollar', 44.93);
INSERT INTO fish (name, price) VALUES ('Silver dory', 48.02);
INSERT INTO fish (name, price) VALUES ('Silver hake', 43.42);
INSERT INTO fish (name, price) VALUES ('Silvertip tetra', 5.49);
INSERT INTO fish (name, price) VALUES ('Silver carp', 5.73);
INSERT INTO fish (name, price) VALUES ('Sixgill ray', 48.89);
INSERT INTO fish (name, price) VALUES ('Sixgill shark', 9.02);
INSERT INTO fish (name, price) VALUES ('Skate', 24.22);
INSERT INTO fish (name, price) VALUES ('Skilfish', 46.52);
INSERT INTO fish (name, price) VALUES ('Slender mola', 43.54);
INSERT INTO fish (name, price) VALUES ('Slender snipe eel', 39.63);
INSERT INTO fish (name, price) VALUES ('Sleeper shark', 14.71);
INSERT INTO fish (name, price) VALUES ('Slickhead', 33.86);
INSERT INTO fish (name, price) VALUES ('Slimehead', 34.01);
INSERT INTO fish (name, price) VALUES ('Slimy mackerel', 23.38);
INSERT INTO fish (name, price) VALUES ('Slimy sculpin', 7.26);
INSERT INTO fish (name, price) VALUES ('Sergeant major', 7.36);
INSERT INTO fish (name, price) VALUES ('Sind danio', 25.56);
INSERT INTO fish (name, price) VALUES ('Smalltooth sawfish', 44.53);
INSERT INTO fish (name, price) VALUES ('Smelt-whiting', 41.39);
INSERT INTO fish (name, price) VALUES ('Smooth dogfish', 8.48);
INSERT INTO fish (name, price) VALUES ('Snailfish', 44.18);
INSERT INTO fish (name, price) VALUES ('Snake eel', 28.22);
INSERT INTO fish (name, price) VALUES ('Snakehead', 7.03);
INSERT INTO fish (name, price) VALUES ('Snake mackerel', 11.29);
INSERT INTO fish (name, price) VALUES ('Snipe eel', 17.85);
INSERT INTO fish (name, price) VALUES ('Snipefish', 45.61);
INSERT INTO fish (name, price) VALUES ('Snubnose eel', 48.39);
INSERT INTO fish (name, price) VALUES ('Snubnose parasitic eel', 46.94);
INSERT INTO fish (name, price) VALUES ('Sockeye salmon', 37.13);
INSERT INTO fish (name, price) VALUES ('Soldierfish', 41.39);
INSERT INTO fish (name, price) VALUES ('South American darter', 6.99);
INSERT INTO fish (name, price) VALUES ('South American lungfish', 25.43);
INSERT INTO fish (name, price) VALUES ('Southern flounder', 34.53);
INSERT INTO fish (name, price) VALUES ('Southern sandfish', 32.26);
INSERT INTO fish (name, price) VALUES ('Southern smelt', 34.03);
INSERT INTO fish (name, price) VALUES ('Spadefish', 30.46);
INSERT INTO fish (name, price) VALUES ('Spaghetti eel', 22.84);
INSERT INTO fish (name, price) VALUES ('Spanish mackerel', 26.43);
INSERT INTO fish (name, price) VALUES ('Spiderfish', 47.08);
INSERT INTO fish (name, price) VALUES ('Spikefish', 38.58);
INSERT INTO fish (name, price) VALUES ('Spinefoot', 17.76);
INSERT INTO fish (name, price) VALUES ('Spiny basslet', 42.39);
INSERT INTO fish (name, price) VALUES ('Spiny dogfish', 28.59);
INSERT INTO fish (name, price) VALUES ('Smalleye squaretail', 26.55);
INSERT INTO fish (name, price) VALUES ('Splitfin', 25.67);
INSERT INTO fish (name, price) VALUES ('Spotted climbing perch', 19.09);
INSERT INTO fish (name, price) VALUES ('Spotted danio', 22.45);
INSERT INTO fish (name, price) VALUES ('Spottail pinfish', 45.98);
INSERT INTO fish (name, price) VALUES ('Springfish', 45.28);
INSERT INTO fish (name, price) VALUES ('Squarehead catfish', 12.0);
INSERT INTO fish (name, price) VALUES ('Squaretail', 39.17);
INSERT INTO fish (name, price) VALUES ('Squawfish', 26.87);
INSERT INTO fish (name, price) VALUES ('Squeaker', 7.47);
INSERT INTO fish (name, price) VALUES ('Squirrelfish', 8.08);
INSERT INTO fish (name, price) VALUES ('Staghorn sculpin', 23.34);
INSERT INTO fish (name, price) VALUES ('Stargazer', 32.48);
INSERT INTO fish (name, price) VALUES ('Starry flounder', 19.82);
INSERT INTO fish (name, price) VALUES ('Steelhead', 46.2);
INSERT INTO fish (name, price) VALUES ('Stickleback', 37.37);
INSERT INTO fish (name, price) VALUES ('Stingray', 10.12);
INSERT INTO fish (name, price) VALUES ('Stonecat', 43.77);
INSERT INTO fish (name, price) VALUES ('Stonefish', 33.01);
INSERT INTO fish (name, price) VALUES ('Spinyfin', 41.89);
INSERT INTO fish (name, price) VALUES ('Stream catfish', 17.05);
INSERT INTO fish (name, price) VALUES ('Striped bass', 27.91);
INSERT INTO fish (name, price) VALUES ('Striped burrfish', 48.81);
INSERT INTO fish (name, price) VALUES ('Sturgeon', 22.99);
INSERT INTO fish (name, price) VALUES ('Sucker', 19.62);
INSERT INTO fish (name, price) VALUES ('Suckermouth armored catfish', 14.74);
INSERT INTO fish (name, price) VALUES ('Surf sardine', 25.21);
INSERT INTO fish (name, price) VALUES ('Surfperch', 39.9);
INSERT INTO fish (name, price) VALUES ('Surgeonfish', 12.23);
INSERT INTO fish (name, price) VALUES ('Swallower', 22.56);
INSERT INTO fish (name, price) VALUES ('Swamp-eel', 5.77);
INSERT INTO fish (name, price) VALUES ('Swampfish', 20.41);
INSERT INTO fish (name, price) VALUES ('Sweeper', 35.81);
INSERT INTO fish (name, price) VALUES ('Swordfish', 38.5);
INSERT INTO fish (name, price) VALUES ('Swordtail', 48.0);
INSERT INTO fish (name, price) VALUES ('Tadpole fish', 24.52);
INSERT INTO fish (name, price) VALUES ('Tailor', 16.44);
INSERT INTO fish (name, price) VALUES ('Taimen', 27.98);
INSERT INTO fish (name, price) VALUES ('Tang', 32.53);
INSERT INTO fish (name, price) VALUES ('Tapetail', 40.03);
INSERT INTO fish (name, price) VALUES ('Tarpon', 32.32);
INSERT INTO fish (name, price) VALUES ('Tarwhine', 25.5);
INSERT INTO fish (name, price) VALUES ('Telescopefish', 47.39);
INSERT INTO fish (name, price) VALUES ('Temperate bass', 24.48);
INSERT INTO fish (name, price) VALUES ('Temperate ocean-bass', 49.07);
INSERT INTO fish (name, price) VALUES ('Temperate perch', 48.77);
INSERT INTO fish (name, price) VALUES ('Tench', 11.11);
INSERT INTO fish (name, price) VALUES ('Tenpounder', 11.91);
INSERT INTO fish (name, price) VALUES ('Tetra', 31.87);
INSERT INTO fish (name, price) VALUES ('Thorny catfish', 18.46);
INSERT INTO fish (name, price) VALUES ('Thornfish', 34.43);
INSERT INTO fish (name, price) VALUES ('Threadfin', 7.1);
INSERT INTO fish (name, price) VALUES ('Threadfin bream', 15.87);
INSERT INTO fish (name, price) VALUES ('Thread-tail', 11.19);
INSERT INTO fish (name, price) VALUES ('Three spot gourami', 42.9);
INSERT INTO fish (name, price) VALUES ('Threespine stickleback', 13.88);
INSERT INTO fish (name, price) VALUES ('Three-toothed puffer', 33.69);
INSERT INTO fish (name, price) VALUES ('Thresher shark', 27.6);
INSERT INTO fish (name, price) VALUES ('Tidewater goby', 48.85);
INSERT INTO fish (name, price) VALUES ('Tiger barb', 33.65);
INSERT INTO fish (name, price) VALUES ('Tigerperch', 29.38);
INSERT INTO fish (name, price) VALUES ('Tiger shark', 18.3);
INSERT INTO fish (name, price) VALUES ('Tiger shovelnose catfish', 40.68);
INSERT INTO fish (name, price) VALUES ('Tilefish', 7.96);
INSERT INTO fish (name, price) VALUES ('Titan triggerfish', 16.65);
INSERT INTO fish (name, price) VALUES ('Tommy ruff', 37.04);
INSERT INTO fish (name, price) VALUES ('Tompot blenny', 48.18);
INSERT INTO fish (name, price) VALUES ('Tonguefish', 12.56);
INSERT INTO fish (name, price) VALUES ('Slipmouth', 20.16);
INSERT INTO fish (name, price) VALUES ('Torrent catfish', 47.26);
INSERT INTO fish (name, price) VALUES ('Torrent fish', 27.31);
INSERT INTO fish (name, price) VALUES ('Trahira', 10.66);
INSERT INTO fish (name, price) VALUES ('Treefish', 29.77);
INSERT INTO fish (name, price) VALUES ('Trevally', 33.04);
INSERT INTO fish (name, price) VALUES ('Triggerfish', 17.66);
INSERT INTO fish (name, price) VALUES ('Triplefin blenny', 45.57);
INSERT INTO fish (name, price) VALUES ('Triplespine', 16.35);
INSERT INTO fish (name, price) VALUES ('Tripletail', 45.88);
INSERT INTO fish (name, price) VALUES ('Trout cod', 31.82);
INSERT INTO fish (name, price) VALUES ('Trout-perch', 5.66);
INSERT INTO fish (name, price) VALUES ('Trumpeter', 42.12);
INSERT INTO fish (name, price) VALUES ('Trumpetfish', 17.42);
INSERT INTO fish (name, price) VALUES ('Trunkfish', 44.03);
INSERT INTO fish (name, price) VALUES ('Tubeblenny', 49.08);
INSERT INTO fish (name, price) VALUES ('Tube-eye', 30.32);
INSERT INTO fish (name, price) VALUES ('Tubeshoulder', 22.83);
INSERT INTO fish (name, price) VALUES ('Tui chub', 46.02);
INSERT INTO fish (name, price) VALUES ('Tuna', 10.67);
INSERT INTO fish (name, price) VALUES ('Turbot', 49.76);
INSERT INTO fish (name, price) VALUES ('Two spotted goby', 23.87);
INSERT INTO fish (name, price) VALUES ('Uaru', 36.56);
INSERT INTO fish (name, price) VALUES ('Vanjaram', 24.26);
INSERT INTO fish (name, price) VALUES ('Velvet belly lanternshark', 7.07);
INSERT INTO fish (name, price) VALUES ('River loach', 20.08);
INSERT INTO fish (name, price) VALUES ('Ricefish', 20.95);
INSERT INTO fish (name, price) VALUES ('Vermilion snapper', 13.45);
INSERT INTO fish (name, price) VALUES ('Velvetfish', 8.49);
INSERT INTO fish (name, price) VALUES ('Velvet catfish', 38.36);
INSERT INTO fish (name, price) VALUES ('Walking catfish', 41.34);
INSERT INTO fish (name, price) VALUES ('Wallago', 48.19);
INSERT INTO fish (name, price) VALUES ('Wahoo', 24.49);
INSERT INTO fish (name, price) VALUES ('Vimba', 19.04);
INSERT INTO fish (name, price) VALUES ('Viperfish', 42.37);
INSERT INTO fish (name, price) VALUES ('Walleye', 26.89);
INSERT INTO fish (name, price) VALUES ('Walu', 39.07);
INSERT INTO fish (name, price) VALUES ('Warmouth', 12.44);
INSERT INTO fish (name, price) VALUES ('Weasel shark', 11.03);
INSERT INTO fish (name, price) VALUES ('Weatherfish', 9.11);
INSERT INTO fish (name, price) VALUES ('Weever', 10.34);
INSERT INTO fish (name, price) VALUES ('Weeverfish', 39.76);
INSERT INTO fish (name, price) VALUES ('Waryfish', 16.15);
INSERT INTO fish (name, price) VALUES ('Whale catfish', 7.11);
INSERT INTO fish (name, price) VALUES ('Whalefish', 26.62);
INSERT INTO fish (name, price) VALUES ('Whale shark', 7.9);
INSERT INTO fish (name, price) VALUES ('White marlin', 27.39);
INSERT INTO fish (name, price) VALUES ('White shark', 30.88);
INSERT INTO fish (name, price) VALUES ('Whitetip reef shark', 16.23);
INSERT INTO fish (name, price) VALUES ('Wobbegong', 29.7);
INSERT INTO fish (name, price) VALUES ('Wolf-eel', 34.09);
INSERT INTO fish (name, price) VALUES ('Wolffish', 46.07);
INSERT INTO fish (name, price) VALUES ('Wolf-herring', 28.29);
INSERT INTO fish (name, price) VALUES ('Worm eel', 15.84);
INSERT INTO fish (name, price) VALUES ('Wrasse', 40.97);
INSERT INTO fish (name, price) VALUES ('Wrymouth', 38.18);
INSERT INTO fish (name, price) VALUES ('Yellow-and-black triplefin', 14.9);
INSERT INTO fish (name, price) VALUES ('Yellowback fusilier', 45.65);
INSERT INTO fish (name, price) VALUES ('Yellowbanded perch', 15.5);
INSERT INTO fish (name, price) VALUES ('Yellowedge grouper', 27.39);
INSERT INTO fish (name, price) VALUES ('Yellow-edged moray', 33.68);
INSERT INTO fish (name, price) VALUES ('Yellow-eye mullet', 23.38);
INSERT INTO fish (name, price) VALUES ('Yellowhead jawfish', 5.24);
INSERT INTO fish (name, price) VALUES ('Yellowfin cutthroat trout', 31.55);
INSERT INTO fish (name, price) VALUES ('Yellowfin grouper', 39.06);
INSERT INTO fish (name, price) VALUES ('Yellowfin pike', 10.64);
INSERT INTO fish (name, price) VALUES ('Yellowfin surgeonfish', 34.72);
INSERT INTO fish (name, price) VALUES ('Yellow jack', 19.17);
INSERT INTO fish (name, price) VALUES ('Yellowmargin triggerfish', 27.26);
INSERT INTO fish (name, price) VALUES ('Yellow moray', 25.36);
INSERT INTO fish (name, price) VALUES ('Yellow perch', 40.04);
INSERT INTO fish (name, price) VALUES ('Yellowtail amberjack', 11.15);
INSERT INTO fish (name, price) VALUES ('Yellowtail barracuda', 36.48);
INSERT INTO fish (name, price) VALUES ('Yellowtail clownfish', 42.79);
INSERT INTO fish (name, price) VALUES ('Yellowtail horse mackerel', 5.2);
INSERT INTO fish (name, price) VALUES ('Yellowtail kingfish', 11.91);
INSERT INTO fish (name, price) VALUES ('Yellowtail snapper', 15.72);
INSERT INTO fish (name, price) VALUES ('Yellow tang', 25.5);
INSERT INTO fish (name, price) VALUES ('Yellow weaver', 42.02);
INSERT INTO fish (name, price) VALUES ('Yellowtail catfish', 10.48);
INSERT INTO fish (name, price) VALUES ('Zander', 28.64);
INSERT INTO fish (name, price) VALUES ('Zebra bullhead shark', 43.48);
INSERT INTO fish (name, price) VALUES ('Zebra danio', 17.29);
INSERT INTO fish (name, price) VALUES ('Zebrafish', 27.53);
INSERT INTO fish (name, price) VALUES ('Waspfish', 26.41);
INSERT INTO fish (name, price) VALUES ('Pacific rudderfish', 22.89);
INSERT INTO fish (name, price) VALUES ('Rock gunnel', 29.9);
INSERT INTO fish (name, price) VALUES ('Stromateidae', 41.94);
